name: build

on:
  push:
    paths:
      - "code/**"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "code/**"
      - ".github/workflows/build.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code
    services:
      neo4j:
        image: neo4j:5-community
        ports:
          - 8687:7687
        env:
          NEO4J_AUTH: neo4j/l3tm31n!
          NEO4JLABS_PLUGINS: '["apoc"]'
      elasticsearch:
        image: elasticsearch/elasticsearch:8.17.3
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: "code/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('code/package-lock.json') }}

      - name: Install
        run: npm install

      - name: build
        run: npm run build

      - name: test
        run: npm test
