name: build

on:
  push:
    paths:
      - "code/**"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "code/**"
      - ".github/workflows/build.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: "code/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('code/package-lock.json') }}

      - name: Install
        run: npm install

      - name: build
        run: npm run build

      - name: test
        run: npm test
